name: Coverage Report Example

on:
  workflow_call:

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download all coverage artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./coverage-artifacts

      - name: Consolidate coverage data
        run: |
          echo "Consolidating coverage data from configured workflows only..."

          # Copy coverage data from artifacts to expected structure

          # Frontend app
          if [ -d "./coverage-artifacts/frontend-coverage" ]; then
            echo "Found frontend coverage"
            mkdir -p ./coverage/apps/frontend
            cp -r ./coverage-artifacts/frontend-coverage/* ./coverage/apps/frontend/ 2>/dev/null || true
          fi

          # Backend app (multiple shards)
          if [ -d "./coverage-artifacts" ]; then
            echo "Consolidating backend coverage from shards..."
            mkdir -p ./coverage/apps/backend
            find ./coverage-artifacts -name "*backend*coverage*" -type d | while read dir; do
              cp -r "$dir"/* ./coverage/apps/backend/ 2>/dev/null || true
            done
          fi

          # MVT server app
          if [ -d "./coverage-artifacts/server-coverage" ]; then
            echo "Found MVT server coverage"
            mkdir -p ./coverage/apps/server
            cp -r ./coverage-artifacts/server-coverage/* ./coverage/apps/server/ 2>/dev/null || true
          fi

          # Pull subscribers app
          if [ -d "./coverage-artifacts/integrations-coverage" ]; then
            echo "Found integrations coverage"
            mkdir -p ./coverage/apps/integrations
            cp -r ./coverage-artifacts/integrations-coverage/* ./coverage/apps/integrations/ 2>/dev/null || true
          fi

          # Libraries (all libraries tested in libraries workflow)
          if [ -d "./coverage-artifacts/libraries-coverage" ]; then
            echo "Found libraries coverage"
            cp -r ./coverage-artifacts/libraries-coverage/* ./coverage/libraries-coverage 2>/dev/null || true
          fi

          # Show what coverage files we have
          echo "Coverage files found:"
          find ./coverage -name "*.json" -o -name "*.xml" -o -name "lcov.info" | head -20

      - name: Check if coverage data exists
        id: check-coverage
        run: |
          if find ./coverage -name "*.json" -o -name "*.xml" -o -name "lcov.info" | grep -q .; then
            echo "has-coverage=true" >> $GITHUB_OUTPUT
            echo "Coverage data found"
          else
            echo "has-coverage=false" >> $GITHUB_OUTPUT
            echo "No coverage data found"
          fi

      - name: Download base coverage for frontend app (target branch)
        uses: dawidd6/action-download-artifact@v6
        id: download-base-coverage-frontend
        continue-on-error: true
        with:
          workflow: ci.yml
          branch: ${{ github.event.pull_request.base.ref || 'staging' }}
          name: coverage-base-frontend
          path: ./coverage-base/apps/frontend
          search_artifacts: true
          workflow_search: true
          workflow_conclusion: ''
          if_no_artifact_found: 'warn'

      - name: Download base coverage for backend app (target branch)
        uses: dawidd6/action-download-artifact@v6
        id: download-base-coverage-backend
        continue-on-error: true
        with:
          workflow: ci.yml
          branch: ${{ github.event.pull_request.base.ref || 'staging' }}
          name: coverage-base-backend
          path: ./coverage-base/apps/backend
          search_artifacts: true
          workflow_search: true
          workflow_conclusion: ''
          if_no_artifact_found: 'warn'

      - name: Download base coverage for server app (target branch)
        uses: dawidd6/action-download-artifact@v6
        id: download-base-coverage-server
        continue-on-error: true
        with:
          workflow: ci.yml
          branch: ${{ github.event.pull_request.base.ref || 'staging' }}
          name: coverage-base-server
          path: ./coverage-base/apps/server
          search_artifacts: true
          workflow_search: true
          workflow_conclusion: ''
          if_no_artifact_found: 'warn'

      - name: Download base coverage for integrations app (target branch)
        uses: dawidd6/action-download-artifact@v6
        id: download-base-coverage-integrations
        continue-on-error: true
        with:
          workflow: ci.yml
          branch: ${{ github.event.pull_request.base.ref || 'staging' }}
          name: coverage-base-integrations
          path: ./coverage-base/apps/integrations
          search_artifacts: true
          workflow_search: true
          workflow_conclusion: ''
          if_no_artifact_found: 'warn'

      - name: Download base coverage for libs (target branch)
        uses: dawidd6/action-download-artifact@v6
        id: download-base-coverage-libs
        continue-on-error: true
        with:
          workflow: ci.yml
          branch: ${{ github.event.pull_request.base.ref || 'staging' }}
          name: coverage-base-libs
          path: ./coverage-base/libraries-coverage
          search_artifacts: true
          workflow_search: true
          workflow_conclusion: ''
          if_no_artifact_found: 'warn'

      # Generate comprehensive coverage report
      - name: Generate coverage report
        uses: your-username/nx-code-coverage@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          no-coverage-ran: ${{ steps.check-coverage.outputs.has-coverage == 'false' }}
          coverage-folder: './coverage'
          coverage-base-folder: './coverage-base'
          hide-coverage-reports: true
          hide-unchanged: true

          comment-title: 'Code Coverage Report'

      - name: Upload coverage for future diffs - frontend app
        if: github.ref == 'refs/heads/staging' && github.event_name == 'push' && hashFiles('./coverage/apps/frontend/**/*') != ''
        uses: actions/upload-artifact@v4
        with:
          name: coverage-base-frontend
          path: ./coverage/apps/frontend
          retention-days: 30

      - name: Upload coverage for future diffs - backend app
        if: github.ref == 'refs/heads/staging' && github.event_name == 'push' && hashFiles('./coverage/apps/backend/**/*') != ''
        uses: actions/upload-artifact@v4
        with:
          name: coverage-base-backend
          path: ./coverage/apps/backend
          retention-days: 30

      - name: Upload coverage for future diffs - server app
        if: github.ref == 'refs/heads/staging' && github.event_name == 'push' && hashFiles('./coverage/apps/server/**/*') != ''
        uses: actions/upload-artifact@v4
        with:
          name: coverage-base-server
          path: ./coverage/apps/server
          retention-days: 30

      - name: Upload coverage for future diffs - integrations app
        if: github.ref == 'refs/heads/staging' && github.event_name == 'push' && hashFiles('./coverage/apps/integrations/**/*') != ''
        uses: actions/upload-artifact@v4
        with:
          name: coverage-base-integrations
          path: ./coverage/apps/integrations
          retention-days: 30

      - name: Upload coverage for future diffs - libs
        if: github.ref == 'refs/heads/staging' && github.event_name == 'push' && hashFiles('./coverage/libraries-coverage/**/*') != ''
        uses: actions/upload-artifact@v4
        with:
          name: coverage-base-libs
          path: ./coverage/libraries-coverage
          retention-days: 30
