name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build action
        run: npm run build

      - name: Package action
        run: |
          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Remove dist from gitignore temporarily and add built files
          sed -i '/^dist\/$/d' .gitignore
          git add dist/ .gitignore

          # Commit if there are changes
          if ! git diff --staged --quiet; then
            git commit -m "Package action for ${{ github.ref_name }}"
            git push origin HEAD:main
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Changes

            See [CHANGELOG.md](CHANGELOG.md) for details.

            ## Usage

            ```yaml
            - uses: MatloobAltaf/nx-code-coverage@${{ github.ref_name }}
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                coverage-folder: './coverage'
            ```
          draft: false
          prerelease: false
